# config.py

# Path to the JSON output generated by the Scrapy spider
SCRAPED_DATA_PATH = "data/output.json"

# Path to save/load the FAISS index
FAISS_INDEX_PATH = "data/faiss_index.index"

# Identifier for the Llama model used with the Groq API via LangChain integration.
LLAMA_MODEL_NAME = "llama-3.1-8b-instant"
